### ISSUE TITLE
[Suggestion] Add a number entry option alongside sliders

### ISSUE THREAD

**Issue by camel-cultist** [lezzthanthree/SIFAS-Dialogue-Sandbox#1]
On my computer it's hard to get a slider to the precise value I want it. It's impossible to get back to 0 after changing the character position slider, for example. If you can, it would be nice if you could input a number value as well as having the slider.

**Comment by lezzthanthree** [comment]
The [feature](https://github.com/lezzthanthree/SIFAS-Dialogue-Sandbox/commit/13c459eba9b21e2fe9f3f9c363cbf5c7549dba57) has now been added. Click the pencil icon and an input pop up will show up.
