### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AngelM009752** [lezzthanthree/SIFAS-Dialogue-Sandbox#2]
Being able to upload our own sprites as we can with the backgrounds and being able to hide the white text box.

**Comment by lezzthanthree** [comment]
These features are now added. You can now [hide the textbox](https://github.com/lezzthanthree/SIFAS-Dialogue-Sandbox/commit/3aa4d8d4dcab6cf3e3817c206327e6b6d7b1011d) and [upload your own sprites](https://github.com/lezzthanthree/SIFAS-Dialogue-Sandbox/commit/920ebd1b5120dfddaba06254d7c5d2abc19ff166).
